# Generated by Django 4.2.7 on 2024-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
